### ISSUE TITLE
pagSeguroButton

### ISSUE THREAD

**Issue by eduardoedson** [LiliumSancta/Flux-CP-PagSeguro#1]
Não estou conseguindo utilizar o addon de donate pagseguro pois, aparentemente, essa função não existe e o botão não aparece. Poderia me ajudar?

`<p><?php echo $this->pagSeguroButton($donationAmount) ?></p>`

**Comment by VitorNaidek** [comment]
Acredito que nas novas versões nem utilizamos mais este botão, mas no final de semana dou uma olhada.

**Comment by VitorNaidek** [comment]
Realmente este botão era utilizado na versão 2.0 na última versão já não utilizamos este botão, recomendo que vc baixe a versão 2.4 e remova a 2.0 do seu fluxo.

**Comment by eduardoedson** [comment]
Onde encontro essa nova versão para baixar? Clonei deste repositório a que estou usando atualmente

**Comment by VitorNaidek** [comment]
É a versão deste repositório mesmo, mas você deve ter misturado os arquivos pois no código atual não existem nenhuma chamada para este método. Se não me falha a memória essa chamada ficava num arquivo na pasta data do fluxcp que não é mais utilizado, por isto recomendo uqe você remova totalmente a versão anterior instalada.

**Comment by eduardoedson** [comment]
Acredito que consegui, muito obrigado! =)
